### ISSUE TITLE
DasContract.Abstraction.Data.Property collection problem

### ISSUE THREAD

**Issue by drozdik-m** [CCMiResearch/DasContract#10]
Property IsCollection of a class DasContract.Abstraction.Data.Property is not very well thought out since it does not work very well with the PropertyType enum. For example, if I design an input that generally reacts to the PropertyType value, I would have to also somehow get the IsCollection property, which is troublesome. However, the biggest flaw is caused by the PropertyType.Data, which is supposed to be an array of bytes. Then PropertyType.Data with IsConnection = true is an array of an array of bytes? There is no possible use case for a 2D byte array. Then, what is I need 2D array for integers? How would I do that?

The best and most coherent way to resolve this is to first delete the IsCollection property, then to extend the PropertyType to have "normal" and collection variants, for example, Int, IntCollection, Uint, UintCollection, ... If you code, you do it this way too, so it only makes sence to do the same thing here.

**Comment by IamMarek** [comment]
The PropertyType is made according to the types in the Solidity programming language. The PropertyType.Data represents a binary file such as image or pdf. A collection of files is therefore a valid usecase.
