### ISSUE TITLE
Custom IDs for process elements / activities

### ISSUE THREAD

**Issue by drozdik-m** [CCMiResearch/DasContract#53]
_Hmmm, yes, Activity_0qtr6ac is very readable and easy to remember._

Seriously, working with randomly generated names is just super annoying. Activity identification should be customizable.

**Comment by drozdik-m** [comment]
Plus, accidentally deleting an activity means I have to rewrite all scripts that mention that activity by id. The new activity will have a different name, and I cannot influence that.

**Comment by klicpjan** [comment]
Agreed, implemented ID editability for both process elements and processes
