### ISSUE TITLE
Go back to the index page button

### ISSUE THREAD

**Issue by drozdik-m** [CCMiResearch/DasContract#73]
I ofter want to create a new contract or upload a different one. There is currently no option to go back to the index page, and it is a bit annoying.

**Comment by klicpjan** [comment]
Don't worry, I already gotchu fam

**Comment by drozdik-m** [comment]
[Woooooooooooooo yeah baby, dats what Ihv been waiting for](https://www.youtube.com/watch?v=sAXZbfLzJUg)
